export const AUTH_USER_CHECK = 'AUTH_USER_CHECK';
export const AUTH_USER_REGISTRATION = 'AUTH_USER_REGISTRATION';
export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';
