export const AUTH_USER_CHECK = 'AUTH_USER_CHECK';
export const AUTH_USER_REQUESTED = 'AUTH_USER_REQUESTED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';
