export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const RESET_SEARCH = 'RESET_SEARCH';
