export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const REGISTRATION = 'REGISTRATION';
export const AUTHORIZATION = 'AUTHORIZATION';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';

export const CHECK_USER_STATUS = 'CHECK_USER_STATUS';
export const CHECK_USER_STATUS_SUCCESS = 'CHECK_USER_STATUS_SUCCESS';
export const CHECK_USER_STATUS_FAILURE = 'CHECK_USER_STATUS_FAILURE';

export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';

export const NOT_FOUND_TOKEN = 'NOT_FOUND_TOKEN';
