export const COMMENTS_REQUESTED = 'COMMENTS_REQUESTED';
export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_COMMENT_REQUESTED = 'ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_RECEIVED = 'ADD_COMMENT_RECEIVED';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';
