export const COMMENTS_REQUESTED = 'COMMENTS_REQUESTED';
export const COMMENTS_RECEIVED = 'COMMENTS_RECEIVED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_COMMENT_REQUESTED = 'ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_RECEIVED = 'ADD_COMMENT_RECEIVED';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';

export const DELETE_COOMENT_REQUESTED = 'DELETE_COOMENT_REQUESTED';
export const DELETE_COOMENT_RECEIVED = 'DELETE_COOMENT_RECEIVED';
export const DELETE_COOMENT_FAILED = 'DELETE_COOMENT_FAILED';

export const SET_COMMENT_ID = 'SET_COMMENT_ID';
