export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';
export const USER_RESET = 'USER_RESET';

export const ADD_POST_REQUESTED = 'ADD_POST_REQUESTED';
export const ADD_POST_RECEIVED = 'ADD_POST_RECEIVED';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';
export const ADD_POST_RESET = 'ADD_POST_RESET';

export const EDIT_PROFILE_REQUESTED = 'EDIT_PROFILE_REQUESTED';
export const EDIT_PROFILE_RECEIVED = 'EDIT_PROFILE_RECEIVED';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';
export const EDIT_PROFILE_RESET = 'EDIT_PROFILE_RESET';
